<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>02promise</title>
    <script>
        const p1 = new Promise(function (resolve, reject) {
            setTimeout(function () {
                reject(new Error('fail'));
                console.log("已经执行了p1中的3秒")
            }, 3000)
        });

        const p2 = new Promise(function (resolve, reject) {
            console.log("执行了p2");
            setTimeout(function () {
                console.log("已经执行了p2中的1秒");
                resolve(p1);
            }, 1000)
        });

        p2.then(function(result){
            console.log(result)
        } => ).catch(error => console.log(error))

    </script>
</head>
<body>
输出结果
<br>
Promise内部-resolve之前
Promise内部-resolve之后
resolved
Hi
</body>
</html>